export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID";
export const UNSET_ACTIVE_USER = "UNSET_ACTIVE_USER";
export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
export const EDITED_MESSAGE = "EDITED_MESSAGE";
export const DETAILS_INFO = "DETAILS_INFO";